- name: Install Networking components
  apt:
    name:
      - neutron-server
      - neutron-plugin-ml2
      - neutron-openvswitch-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
    state: present

- name: Configure Networking server
  block:
    - name: Edit neutron.conf
      blockinfile:
        path: /etc/neutron/neutron.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK -- neutron.conf"
        block: |
          [database]
          connection = mysql+pymysql://neutron:password@controller/neutron

          [DEFAULT]
          core_plugin = ml2
          service_plugins =
          transport_url = rabbit://openstack:password@controller
          auth_strategy = keystone

          [keystone_authtoken]
          www_authenticate_uri = http://controller:5000/v3
          auth_url = http://controller:5000/v3
          memcached_servers = controller:11211
          auth_type = password
          project_domain_name = Default
          user_domain_name = Default
          project_name = service
          username = neutron
          password = password

          [oslo_concurrency]
          lock_path = /var/lib/neutron/tmp
      notify: restart neutron-server

- name: Edit ml2_conf.ini
  blockinfile:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    marker: "# {mark} ANSIBLE MANAGED BLOCK -- ml2_conf.ini"
    block: |
      [ml2]
      type_drivers = flat,vlan
      tenant_network_types =
      mechanism_drivers = openvswitch
      extension_drivers = port_security

      [ml2_type_flat]
      flat_networks = provider
  notify: restart neutron-server

- name: Edit openvswitch_agent.ini
  blockinfile:
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    marker: "# {mark} ANSIBLE MANAGED BLOCK -- openvswitch_agent.ini"
    block: |
      [ovs]
      bridge_mappings = provider:PROVIDER_INTERFACE_NAME

      [securitygroup]
      enable_security_group = true
      firewall_driver = openvswitch
  notify: restart neutron-openvswitch-agent

- name: Edit dhcp_agent.ini
  blockinfile:
    path: /etc/neutron/dhcp_agent.ini
    marker: "# {mark} ANSIBLE MANAGED BLOCK -- dhcp_agent.ini"
    block: |
      [DEFAULT]
      interface_driver = openvswitch
      dhcp_driver = neutron.agent.linux.dhcp.Dnsmasq
      enable_isolated_metadata = true
  notify: restart neutron-dhcp-agent

- name: Configure metadata agent
  blockinfile:
    path: /etc/neutron/metadata_agent.ini
    marker: "# {mark} ANSIBLE MANAGED BLOCK -- metadata_agent.ini"
    block: |
      [DEFAULT]
      nova_metadata_host = controller
      metadata_proxy_shared_secret = METADATA_SECRET
  notify: restart neutron-metadata-agent

- name: Configure Compute service to use Networking service
  blockinfile:
    path: /etc/nova/nova.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK -- nova.conf"
    block: |
      [neutron]
      auth_url = http://controller:5000/v3
      auth_type = password
      project_domain_name = Default
      user_domain_name = Default
      region_name = RegionOne
      project_name = service
      username = neutron
      password = password
      service_metadata_proxy = true
      metadata_proxy_shared_secret = METADATA_SECRET
  notify: restart nova-api

- name: Populate the database
  become: true
  command: >
    neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
