---
- name: restart neutron-server
  service:
    name: neutron-server
    state: restarted

- name: restart neutron-openvswitch-agent
  service:
    name: neutron-openvswitch-agent
    state: restarted

- name: restart neutron-dhcp-agent
  service:
    name: neutron-dhcp-agent
    state: restarted

- name: restart neutron-metadata-agent
  service:
    name: neutron-metadata-agent
    state: restarted

- name: restart nova-api
  service:
    name: nova-api
    state: restarted
