---
- name: Install Horizon packages
  apt:
    name: openstack-dashboard
    state: present

- name: Configure Horizon settings
  blockinfile:
    path: /etc/openstack-dashboard/local_settings.py
    marker: "# {mark} ANSIBLE MANAGED BLOCK -- local_settings.py"
    block: |
      OPENSTACK_HOST = "controller"

      ALLOWED_HOSTS = ['one.example.com', 'two.example.com']

      SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
      CACHES = {
          'default': {
               'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
               'LOCATION': 'controller:11211',
          }
      }

      OPENSTACK_KEYSTONE_URL = "http://%s/identity/v3" % OPENSTACK_HOST

      OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT = True

      OPENSTACK_API_VERSIONS = {
          "identity": 3,
          "image": 2,
          "volume": 3,
      }

      OPENSTACK_KEYSTONE_DEFAULT_DOMAIN = "Default"

      OPENSTACK_KEYSTONE_DEFAULT_ROLE = "user"

      OPENSTACK_NEUTRON_NETWORK = {
          'enable_router': False,
          'enable_quotas': False,
          'enable_ipv6': False,
          'enable_distributed_router': False,
          'enable_ha_router': False,
          'enable_fip_topology_check': False,
      }

      TIME_ZONE = "UTC"
  notify: Reload Apache to apply configuration changes

- name: Add WSGIApplicationGroup directive to openstack-dashboard.conf
  lineinfile:
    path: /etc/apache2/conf-available/openstack-dashboard.conf
    line: "WSGIApplicationGroup %{GLOBAL}"
    insertafter: BOF
  notify: Reload Apache to apply configuration changes
